site_name: TRAINING MODULES
site_url: https://nu-teams.github.io/Arduino_Zero_To_Hero/
theme:
  name: material
  logo: assets/img/NUTeams_simplified_white_on_trans.png
  favicon: assets/img/NUTeams_favicon.png
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: blue
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  #Emojis & Symbols extension
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  #Callouts extension
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  #Code block extension
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

  #Content Tabs
  - pymdownx.tabbed:
      alternate_style: true